### Apresentação do Projeto
Proposta para a construção de uma aplicação que realiza análise de sentimentos à presidência.

Intalação das Bibliotecas

In [1]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.3.4-py3-none-any.whl (35 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.3.4

Importando as Bibliotecas

In [2]:
import snscrape.modules.twitter as sntwitter
#Manipulação de Dados
import pandas as pd

In [3]:
maximo_de_tweets=50

### Lula

In [4]:
lista_de_tweets_lula = []

In [5]:
for i, tweet in enumerate (sntwitter.TwitterSearchScraper(['lula']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_lula.append([tweet.date, tweet.id, tweet.content])

In [6]:
type(lista_de_tweets_lula)

list

In [7]:
dataframe_tweets_lula = pd.DataFrame(lista_de_tweets_lula, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [8]:
dataframe_tweets_lula.head ()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...

In [9]:
dataframe_tweets_lula['Candidato'] = 'Lula'

In [10]:
dataframe_tweets_lula.head ()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...,Lula
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...,Lula
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...,Lula
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...,Lula

### Bolsonaro

In [11]:
lista_de_tweets_bolsonaro = []

In [12]:
for i, tweet in enumerate (sntwitter.TwitterSearchScraper(['bolsonaro']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_bolsonaro.append([tweet.date, tweet.id, tweet.content])

In [13]:
dataframe_tweets_bolsonaro = pd.DataFrame(lista_de_tweets_bolsonaro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [14]:
dataframe_tweets_bolsonaro.head ()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:17:32+00:00,1553520196110917633,@jairbolsonaro Famoso gadogram
1,2022-07-30 23:17:32+00:00,1553520195670622208,@Pauloeuaqui1 @jairbolsonaro Quem tem medo é o...
2,2022-07-30 23:17:31+00:00,1553520194328330242,"Fugir para os EUA,com certeza não vai garantir..."
3,2022-07-30 23:17:31+00:00,1553520193506271232,@Antnio3070 @MarcioM61326104 @adinaelsilva @Al...
4,2022-07-30 23:17:31+00:00,1553520192369688578,"O Manifesto do Direito via USP, com 500 mil as..."

In [15]:
dataframe_tweets_bolsonaro['Candidato'] = 'Bolsonaro'

In [16]:
dataframe_tweets_bolsonaro.head ()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:17:32+00:00,1553520196110917633,@jairbolsonaro Famoso gadogram,Bolsonaro
1,2022-07-30 23:17:32+00:00,1553520195670622208,@Pauloeuaqui1 @jairbolsonaro Quem tem medo é o...,Bolsonaro
2,2022-07-30 23:17:31+00:00,1553520194328330242,"Fugir para os EUA,com certeza não vai garantir...",Bolsonaro
3,2022-07-30 23:17:31+00:00,1553520193506271232,@Antnio3070 @MarcioM61326104 @adinaelsilva @Al...,Bolsonaro
4,2022-07-30 23:17:31+00:00,1553520192369688578,"O Manifesto do Direito via USP, com 500 mil as...",Bolsonaro

### Ciro Gomes

In [17]:
lista_de_tweets_ciro = []

In [18]:
for i, tweet in enumerate (sntwitter.TwitterSearchScraper(['ciro gomes']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_ciro.append([tweet.date, tweet.id, tweet.content])

In [19]:
dataframe_tweets_ciro = pd.DataFrame(lista_de_tweets_ciro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [20]:
dataframe_tweets_ciro.head ()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:17:46+00:00,1553520253463937026,Já saiu a toalha do Ciro Gomes hahaha https://...
1,2022-07-30 23:17:31+00:00,1553520192399065088,@cirogomes MEIA DUZIA
2,2022-07-30 23:17:11+00:00,1553520106633891840,@cirogomes Hahahhahahahahhahahahahahahhahahaha...
3,2022-07-30 23:17:04+00:00,1553520077408030725,@Eu53122667 @cirogomes
4,2022-07-30 23:17:04+00:00,1553520077009522689,@parox40 @cirogomes Bah... na cara não...\nMag...

In [21]:
dataframe_tweets_ciro['Candidato'] = 'Ciro Gomes'

In [22]:
dataframe_tweets_ciro.head ()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:17:46+00:00,1553520253463937026,Já saiu a toalha do Ciro Gomes hahaha https://...,Ciro Gomes
1,2022-07-30 23:17:31+00:00,1553520192399065088,@cirogomes MEIA DUZIA,Ciro Gomes
2,2022-07-30 23:17:11+00:00,1553520106633891840,@cirogomes Hahahhahahahahhahahahahahahhahahaha...,Ciro Gomes
3,2022-07-30 23:17:04+00:00,1553520077408030725,@Eu53122667 @cirogomes,Ciro Gomes
4,2022-07-30 23:17:04+00:00,1553520077009522689,@parox40 @cirogomes Bah... na cara não...\nMag...,Ciro Gomes

In [23]:
dataframe_final = pd.concat([dataframe_tweets_lula, dataframe_tweets_bolsonaro, dataframe_tweets_ciro], axis = 0)

In [24]:
dataframe_final.head ()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...,Lula
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...,Lula
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...,Lula
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...,Lula

In [25]:
dataframe_final['Candidato'].unique()

array(['Lula', 'Bolsonaro', 'Ciro Gomes'], dtype=object)

In [26]:
dataframe_final.to_csv('datafreame_final_candidatos.csv', sep=',', index=False)