### Etapa 3 - EDA, Storytelling e Visualização

In [1]:
import pandas as pd
import re

In [2]:
dataframe_final_candidatos = pd.read_csv("etapa2_datafreame_final_candidatos.csv")

In [3]:
dataframe_final_candidatos.head ()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...,Lula
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...,Lula
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...,Lula
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...,Lula

In [4]:
dataframe_final_candidatos.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data_Hora  153 non-null    object
 1   IdTweet    153 non-null    int64
 2   Tweet      153 non-null    object
 3   Candidato  153 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [5]:
dataframe_final_candidatos.isnull ().sum ()

Data_Hora    0
IdTweet      0
Tweet        0
Candidato    0
dtype: int64

In [6]:
dataframe_final_candidatos[ 'Tweet_limpo'] = dataframe_final_candidatos['Tweet']

In [7]:
dataframe_final_candidatos.head ()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...,Lula,@LulaOficial @dilmabr Alguém de vcs checa isso...
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...,Lula,Presidente: Lula; Senador:?; Deputado Federal:...
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...,Lula,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...,Lula,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...

In [8]:
def limpeza_do_texto(tweet):
  tweet = tweet.lower()
  tweet = re.sub ('\n', '', tweet)
  tweet = re.sub ('@[^\s]+','', tweet)
  tweet = re.sub ('\B#\S+','', tweet)
  tweet = re.sub ('https?://\S+|www\.\S+','', tweet)
  return tweet

In [9]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet'].apply(lambda i:limpeza_do_texto(i))

In [10]:
dataframe_final_candidatos.head ()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-30 23:17:46+00:00,1553520255238119424,@LulaOficial @dilmabr Alguém de vcs checa isso...,Lula,alguém de vcs checa isso .
1,2022-07-30 23:17:46+00:00,1553520253535227906,Presidente: Lula; Senador:?; Deputado Federal:...,Lula,presidente: lula; senador:?; deputado federal:...
2,2022-07-30 23:17:45+00:00,1553520252608192512,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula,"trocaram de fotógrafo, ou aprenderam a mon..."
3,2022-07-30 23:17:45+00:00,1553520251211505664,@MARCOSDANI1 @LulaOficial NÃO...BEM REAL...,Lula,não...bem real...
4,2022-07-30 23:17:45+00:00,1553520250263687168,@WesleyAHS11s @LulaOficial #BolsonaroReeleitoE...,Lula,

In [11]:
dataframe_final_candidatos.to_csv('dataframe_final_candidatos_pronto_para_sentimento.csv', sep=',', index=False)